"""Study 5 — manuscript table + in-text-macro builder (Step 4 typesetting pipeline).

Reads ONLY immutable analysis outputs and emits LaTeX fragments. No coefficient,
SE, p-value or N is ever typed into a .tex file by hand; every number here is read
from a results file and formatted.

Sources (all hash-frozen upstream):
  results/stage2/CODEX-S5-TABLES-20260909-001/T1_drop_table.csv          -> tab_sample.tex
  results/stage2/CODEX-S5-TABLES-20260909-001/T2_descriptives.csv        -> tab_descriptives.tex
  results/stage2/CODEX-S5-TABLES-20260909-001/T3_primary_moderation.csv  }
  results/stage2/CODEX-S5-EXP-20260909-002/result.json (models, bh_family,}-> tab_primary.tex, tab_mechanism.tex,
      descriptives, vietnam, primary)                                    }   tab_secondary.tex, tab_robustness.tex
  results/stage2/CODEX-S5-TABLES-20260909-001/T4_mechanism.csv
  results/stage2/CODEX-S5-TABLES-20260909-001/T5_secondary_placebo.csv
  results/stage2/CODEX-S5-TABLES-20260909-001/T6_robustness.csv
  results/stage2/CODEX-S5-EXP-20260909-002/interaction_grid.csv          -> tab_robustness.tex (adversarial rows)
  results/stage3/CODEX-S5-DB-INTEGRITY-20260910-001/result.json          -> tab_robustness.tex (CHN/SAU row), macros
  results/stage3/CODEX-S5-CTRLXMOD-REPRO-20260910-001/result.json        -> tab_robustness.tex (control x moderator), macros
  results/stage3/CLAUDE-S5R-CTRLXMOD-WR2-20260910-001/result.json        -> within-R2 macros
  results/stage3/CODEX-S5-SAMPLE-COMPOSITION-20260910-001/result.json    -> sample-composition macros

Outputs: papers/study_05/manuscript/tables/*.tex and papers/study_05/manuscript/estimates.tex

Usage:  python code/study_05_crosscountry/tables/build_tables.py
"""
from __future__ import annotations

import csv
import json
import math
from datetime import datetime, timezone
from pathlib import Path

PROJECT = Path(__file__).resolve().parents[3]
TAB = PROJECT / "results/stage2/CODEX-S5-TABLES-20260909-001"
EXP = PROJECT / "results/stage2/CODEX-S5-EXP-20260909-002"
S3 = PROJECT / "results/stage3"
OUT_TAB = PROJECT / "papers/study_05/manuscript/tables"
OUT_MACRO = PROJECT / "papers/study_05/manuscript/estimates.tex"

# ---------------------------------------------------------------- helpers ------

def read_csv(path: Path) -> list[dict]:
    with path.open(encoding="utf-8") as fh:
        return list(csv.DictReader(fh))


def load_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def pp(x, d: int = 3) -> str:
    """Percentage points, d decimals."""
    return f"{100.0 * float(x):.{d}f}"


def num(x, d: int = 3) -> str:
    return f"{float(x):.{d}f}"


def pval(p) -> str:
    if p in (None, "", "nan") or (isinstance(p, float) and math.isnan(p)):
        return "--"
    p = float(p)
    if p < 1e-4:
        return "$<$0.0001"
    if p < 0.001:
        return f"{p:.5f}"
    return f"{p:.3f}"


def stars(p) -> str:
    if p in (None, "", "nan"):
        return ""
    p = float(p)
    return "***" if p < 0.01 else "**" if p < 0.05 else "*" if p < 0.10 else ""


def se_line(se, d: int = 3) -> str:
    return f"({100.0 * float(se):.{d}f})"


def ci(lo, hi, d: int = 2) -> str:
    return f"[{100.0*float(lo):.{d}f}, {100.0*float(hi):.{d}f}]"


def intfmt(n) -> str:
    return f"{int(round(float(n))):,}"


HEADER = "% GENERATED by code/study_05_crosscountry/tables/build_tables.py -- DO NOT EDIT BY HAND\n"

# ---------------------------------------------------------------- load ---------

t1 = read_csv(TAB / "T1_drop_table.csv")
t2 = read_csv(TAB / "T2_descriptives.csv")
t4 = read_csv(TAB / "T4_mechanism.csv")
t5 = read_csv(TAB / "T5_secondary_placebo.csv")
t6 = read_csv(TAB / "T6_robustness.csv")
grid = read_csv(EXP / "interaction_grid.csv")
exp = load_json(EXP / "result.json")
models = exp["models"]
bh = {r["test"]: r for r in exp["bh_family"]}
vnm = exp["vietnam"]
desc = exp["descriptives"]

dbint = load_json(S3 / "CODEX-S5-DB-INTEGRITY-20260910-001/result.json")
ctrlx = load_json(S3 / "CODEX-S5-CTRLXMOD-REPRO-20260910-001/result.json")
wr2 = load_json(S3 / "CLAUDE-S5R-CTRLXMOD-WR2-20260910-001/result.json")
adv = load_json(S3 / "CODEX-S5-AUDIT-20260909-001/adversarial_checks.json")["checks"]
try:
    comp = load_json(S3 / "CODEX-S5-SAMPLE-COMPOSITION-20260910-001/result.json")
except FileNotFoundError:
    comp = {}
try:
    m7ci = load_json(S3 / "CLAUDE-S5R-M7-VNM-CI-20260910-001/result.json")
except FileNotFoundError:
    m7ci = {}

OUT_TAB.mkdir(parents=True, exist_ok=True)


def write(name: str, body: str) -> None:
    # threeparttable ties its notes to the (possibly very wide) natural table width,
    # which overflows the text block. Replace it with: adjustbox around the tabular
    # (shrinks only when needed) + a full-width minipage for the notes.
    body = (
        body.replace(r"\begin{threeparttable}", "")
        .replace(r"\end{threeparttable}", "")
        .replace(r"\begin{tabular}", r"\begin{adjustbox}{max width=\textwidth}" + "\n" + r"\begin{tabular}")
        .replace(r"\end{tabular}", r"\end{tabular}" + "\n" + r"\end{adjustbox}")
        .replace(r"\begin{tablenotes}[flushleft]\footnotesize",
                 r"\smallskip" + "\n" + r"\begin{minipage}{\linewidth}\footnotesize \emph{Notes.}")
        .replace(r"\item ", "")
        .replace(r"\end{tablenotes}", r"\end{minipage}")
    )
    (OUT_TAB / name).write_text(HEADER + body + "\n", encoding="utf-8")
    print(f"  wrote tables/{name}")


def t6row(key):
    return next((x for x in t6 if x["variant"] == key), None)


# ---------------------------------------------------------------- Table 1 ------

def build_sample() -> None:
    label = {
        "fin22a_valid_1_or_2": r"Valid formal-borrowing response ($\mathit{fin22a}\in\{1,2\}$)",
        "anydigpayment_nonmissing": r"\quad + non-missing digital-payment indicator",
        "account_fin_nonmissing": r"\quad + non-missing account ownership",
        "female_nonmissing": r"\quad + non-missing sex",
        "age_nonmissing": r"\quad + non-missing age",
        "educ_nonmissing": r"\quad + non-missing education",
        "inc_q_nonmissing": r"\quad + non-missing income quintile",
        "urbanicity_nonmissing": r"\quad + non-missing urbanicity",
        "moderator_iso3_match": r"\quad + 2019 coverage moderator merged by ISO3",
    }
    rows = []
    for r in t1:
        exited = r["economies_exited"].strip()
        if exited and ";" not in exited:
            note = f"({exited} exits)"
        elif exited:
            note = f"({exited.count(';')+1} economies exit)"
        else:
            note = ""
        rows.append(
            f"{label[r['step']]} & {intfmt(r['rows_after'])} & {intfmt(r['economies_after'])} & {note} \\\\"
        )
    body = rf"""\begin{{table}}[htbp]
\centering
\caption{{Sample construction.}}
\label{{tab:sample}}
\begin{{threeparttable}}
\begin{{tabular}}{{l r r l}}
\toprule
Step & {{Adults}} & {{Economies}} & \\
\midrule
{chr(10).join(rows)}
\bottomrule
\end{{tabular}}
\begin{{tablenotes}}[flushleft]\footnotesize
\item Deterministic listwise construction from the 2024 Global Findex microdata
(catalogue 7860). ``Don't know'' and ``refused'' on the outcome are dropped before
step 1. The moderator merges to every remaining economy.
\end{{tablenotes}}
\end{{threeparttable}}
\end{{table}}"""
    write("tab_sample.tex", body)


# ---------------------------------------------------------------- Table 2 ------

def build_descriptives() -> None:
    def g(panel, var):
        for r in t2:
            if r["panel"] == panel and r["variable"] == var:
                return r
        raise KeyError((panel, var))

    ind_vars = [("formal_borrow", "Formal borrowing"), ("account_fin", "Account at a financial institution"),
                ("female_d", "Female"), ("age", "Age (years)"), ("urban_d", "Urban")]
    rows_ind = []
    for key, lab in ind_vars:
        o, z, one = g("overall", key), g("anydigpayment_0", key), g("anydigpayment_1", key)
        fmt = (lambda v: num(v, 1)) if key == "age" else (lambda v: num(v, 3))
        rows_ind.append(f"{lab} & {fmt(o['weighted_mean'])} & {fmt(z['weighted_mean'])} & {fmt(one['weighted_mean'])} & \\\\")

    mod_vars = [("any_cov", "2019 credit-information coverage (\\%)"),
                ("bureau_cov", "\\quad 2019 private-bureau coverage (\\%)"),
                ("registry_cov", "\\quad 2019 public-registry coverage (\\%)"),
                ("depth_credit_info_0_8", "Depth-of-credit-information index (0--8)"),
                ("legal_rights_0_12", "Strength-of-legal-rights index (0--12)")]
    rows_mod = []
    for key, lab in mod_vars:
        r = g("economy_moderator", key)
        rows_mod.append(
            f"{lab} & {num(r['weighted_mean'],1)} & {num(r['median'],1)} & "
            f"{{[{num(r['p25'],1)}, {num(r['p75'],1)}]}} & {num(r['vietnam'],1)} \\\\"
        )
    n_ind = intfmt(g("overall", "formal_borrow")["N"])
    n0 = intfmt(g("anydigpayment_0", "formal_borrow")["N"])
    n1 = intfmt(g("anydigpayment_1", "formal_borrow")["N"])

    body = rf"""\begin{{table}}[htbp]
\centering
\caption{{Descriptive statistics.}}
\label{{tab:descriptives}}
\begin{{threeparttable}}
\begin{{tabular}}{{l r r r l}}
\toprule
\multicolumn{{5}}{{l}}{{\emph{{Panel A. Individual characteristics (survey-weighted means)}}}} \\
 & {{All}} & {{No digital}} & {{Digital}} & \\
 & {{($N={n_ind}$)}} & {{payment ($N={n0}$)}} & {{payment ($N={n1}$)}} & \\
\midrule
{chr(10).join(rows_ind)}
\midrule
\multicolumn{{5}}{{l}}{{\emph{{Panel B. Economy-level 2019 moderator ($G=97$ economies, unweighted)}}}} \\
 & {{Mean}} & {{Median}} & {{[p25, p75]}} & {{Vietnam}} \\
\cmidrule(lr){{1-5}}
{chr(10).join(rows_mod)}
\bottomrule
\end{{tabular}}
\begin{{tablenotes}}[flushleft]\footnotesize
\item Panel A: means weighted by \texttt{{w\_equal}} (each economy sums to one).
Panel B: one row per economy, unweighted; the moderator used in estimation is the
negative $z$-score of the coverage measure (\texttt{{lowcov2019\_z}}).
\end{{tablenotes}}
\end{{threeparttable}}
\end{{table}}"""
    write("tab_descriptives.tex", body)


# ---------------------------------------------------------------- Table 3 ------

def coef_cell(m: str, term: str, d: int = 3):
    c = models[m]["coefficients"][term]
    return f"{100.0*c['estimate']:.{d}f}{stars(c['p_cluster'])}", se_line(c["se_cluster"], d)


def build_primary() -> None:
    m1, m2 = models["M1"], models["M2"]
    rows = []

    def add(label, term):
        e1 = s1 = e2 = s2 = "{--}"
        if term in m1["coefficients"]:
            e1, s1 = coef_cell("M1", term)
        if term in m2["coefficients"]:
            e2, s2 = coef_cell("M2", term)
        rows.append(f"{label} & {e1} & {e2} \\\\")
        rows.append(f" & {s1} & {s2} \\\\[2pt]")

    add(r"Digital payment ($\beta_1$)", "anydigpayment")
    add(r"Digital payment $\times$ lower 2019 coverage ($\beta_3$)", "anydigpayment:lowcov2019_z")
    add(r"Account at FI ($\beta_2$)", "account_fin")
    add(r"Account at FI $\times$ lower 2019 coverage ($\beta_4$)", "account_fin:lowcov2019_z")

    wild_m1 = next((r["p_wild"] for r in read_csv(TAB / "T3_primary_moderation.csv")
                    if r["model"] == "M1" and r["term"] == "anydigpayment"), "--")
    b3 = m2["coefficients"]["anydigpayment:lowcov2019_z"]
    wild_b3 = b3.get("p_wild_score_rademacher_999", "--")

    body = rf"""\begin{{table}}[htbp]
\centering
\caption{{Digital payments, formal borrowing and the 2019 coverage moderator.}}
\label{{tab:primary}}
\begin{{threeparttable}}
\begin{{tabular}}{{l r r}}
\toprule
 & (1) M1 & (2) M2 \\
 & {{Association}} & {{Moderation}} \\
\midrule
{chr(10).join(rows)}
\midrule
Demographic controls & {{Yes}} & {{Yes}} \\
Economy fixed effects & {{Yes}} & {{Yes}} \\
Clusters (economies) & {{{m1['G']}}} & {{{m2['G']}}} \\
Observations & {{{intfmt(m1['N'])}}} & {{{intfmt(m2['N'])}}} \\
Within-$R^2$ & {{{num(m1['within_r2'], 4)}}} & {{{num(m2['within_r2'], 4)}}} \\
\bottomrule
\end{{tabular}}
\begin{{tablenotes}}[flushleft]\footnotesize
\item Survey-weighted (\texttt{{w\_equal}}) linear probability models; coefficients and
standard errors in percentage points. Economy-clustered (CR1) standard errors in
parentheses. Demographic controls: female, age (centred) and its square, education
(3 categories), within-economy income quintile (5), urban. $\beta_3$ is the
pre-registered test. Rademacher wild-cluster-bootstrap $p$ (999 replications):
$\beta_1$ in M1, $p={wild_m1}$; $\beta_3$ in M2, $p={wild_b3}$.
Stars: *** $p<0.01$, ** $p<0.05$, * $p<0.10$ (economy-clustered).
\end{{tablenotes}}
\end{{threeparttable}}
\end{{table}}"""
    write("tab_primary.tex", body)


# ---------------------------------------------------------------- Table 4 ------

def build_mechanism() -> None:
    rows = []

    def add(label, m, term):
        c = models[m]["coefficients"][term]
        rows.append(f"{label} & {100.0*c['estimate']:.3f}{stars(c['p_cluster'])} & {se_line(c['se_cluster'])} & {pval(c['p_cluster'])} \\\\")

    add(r"Receiving a digital payment (M3a)", "M3a", "receive_dig")
    add(r"Making a digital payment (M3a)", "M3a", "make_dig")
    rows.append(r"\midrule")
    add(r"Receiving $\times$ lower 2019 coverage (M3b)", "M3b", "receive_dig:lowcov2019_z")
    add(r"Making $\times$ lower 2019 coverage (M3b)", "M3b", "make_dig:lowcov2019_z")
    n, g = models["M3a"]["N"], models["M3a"]["G"]
    body = rf"""\begin{{table}}[htbp]
\centering
\caption{{Mechanism split: receiving versus making digital payments.}}
\label{{tab:mechanism}}
\begin{{threeparttable}}
\begin{{tabular}}{{l r c l}}
\toprule
 & Coefficient & (CR1 SE) & $p$ \\
\midrule
{chr(10).join(rows)}
\midrule
Observations & \multicolumn{{3}}{{c}}{{{intfmt(n)}}} \\
Clusters (economies) & \multicolumn{{3}}{{c}}{{{g}}} \\
\bottomrule
\end{{tabular}}
\begin{{tablenotes}}[flushleft]\footnotesize
\item Mechanism sub-sample (non-missing receive and make indicators). M3a and M3b
carry the full frozen control set and economy fixed effects. Percentage points;
economy-clustered (CR1) standard errors. The substitution reading predicts the
receiving interaction to be the more negative; it is instead near zero.
\end{{tablenotes}}
\end{{threeparttable}}
\end{{table}}"""
    write("tab_mechanism.tex", body)


# ---------------------------------------------------------------- Table 5 ------

def build_secondary() -> None:
    spec = [
        ("Mobile-loan-app use", "M4_mobile_loan_app", "mobile_b3"),
        ("Emergency loan from a formal source", "M4_emergency_loan_source", "emergency_loan_source_b3"),
        ("Informal borrowing (placebo)", "M4_informal_borrow", "informal_b3"),
    ]
    rows = []
    for lab, m, bkey3 in spec:
        c1 = models[m]["coefficients"]["anydigpayment"]
        c3 = models[m]["coefficients"]["anydigpayment:lowcov2019_z"]
        q3 = bh[bkey3]["q_bh"]
        rows.append(
            f"{lab} & {100.0*c1['estimate']:.3f}{stars(c1['p_cluster'])} & "
            f"{100.0*c3['estimate']:.3f}{stars(c3['p_cluster'])} & {pval(c3['p_cluster'])} & "
            f"{num(q3,3)} & {intfmt(models[m]['N'])} \\\\"
        )
    body = rf"""\begin{{table}}[htbp]
\centering
\caption{{Secondary outcomes and the informal-borrowing placebo.}}
\label{{tab:secondary}}
\begin{{threeparttable}}
\begin{{tabular}}{{l r r l r r}}
\toprule
Outcome & $\beta_1$ & $\beta_3$ & $p(\beta_3)$ & BH $q(\beta_3)$ & $N$ \\
\midrule
{chr(10).join(rows)}
\bottomrule
\end{{tabular}}
\begin{{tablenotes}}[flushleft]\footnotesize
\item Each row is one M2-form regression on the named outcome, full control set and
economy fixed effects, percentage points, economy-clustered (CR1). Benjamini--Hochberg
$q$-values are computed over the frozen nine-hypothesis secondary family. The
substitution reading predicts the informal-borrowing $\beta_3$ near zero; it is
positive and survives the correction.
\end{{tablenotes}}
\end{{threeparttable}}
\end{{table}}"""
    write("tab_secondary.tex", body)


# ---------------------------------------------------------------- Table 6 ------

def build_robustness() -> None:
    gridmap = {r["model"]: r for r in grid}
    b3 = models["M2"]["coefficients"]["anydigpayment:lowcov2019_z"]

    def row_t6(key, label, note=""):
        r = t6row(key)
        est = f"{100.0*float(r['estimate']):.3f}"
        p = pval(r["p_cluster"])
        n = intfmt(r["N"]) if r["N"] not in ("", None, "nan") else "{--}"
        gg = str(int(round(float(r["G"])))) if r["G"] not in ("", None, "nan") else "{--}"
        return f"{label} & {est} & {p} & {n} & {gg} & {note} \\\\"

    def row_grid(key, label, note=""):
        r = gridmap[key]
        est = f"{100.0*float(r['estimate']):.3f}"
        p = pval(r["p_cluster"]) if r["p_cluster"] not in ("", None) else "--"
        n = intfmt(r["N"]) if r["N"] not in ("", None) else "{--}"
        gg = str(int(round(float(r["G"])))) if r["G"] not in ("", None) else "{--}"
        return f"{label} & {est} & {p} & {n} & {gg} & {note} \\\\"

    rows = [
        f"M2 baseline & {pp(b3['estimate'])} & {pval(b3['p_cluster'])} & {intfmt(models['M2']['N'])} & {models['M2']['G']} & \\\\",
        r"\addlinespace",
        row_t6("M6_1_unweighted", "Unweighted"),
        row_t6("M6_1_population", "Population weights"),
        row_t6("M6_3_drop_high_income", "Drop 6 high-income economies", "$z$ re-computed"),
        row_t6("M6_5_country_controls", "+ country controls $\\times$ digital payment"),
        row_t6("M6_8_internet", "+ internet-use control"),
        row_t6("M6_10_inwork", "+ employment control"),
        row_t6("M6_6_n_ge_500", "Economies with $N\\geq 500$"),
        r"\addlinespace",
        row_t6("M6_4_lowdepth2019_z", "Moderator = depth-of-information proxy", "same sign, imprecise"),
        row_t6("M6_4_lowrights2019_z", "Moderator = legal-rights proxy", "wrong sign, imprecise"),
        r"\addlinespace",
    ]
    def row_adv(key, label, note=""):
        r = adv[key]
        return (f"{label} & {pp(r['estimate'])} & {pval(r['p'])} & "
                f"{intfmt(r['N'])} & {r['G']} & {note} \\\\")

    rows.append(row_adv("account_holders_only", "Restrict to account holders", "imprecise"))
    rows.append(row_adv("drop_zero_coverage", "Drop zero-coverage economies"))
    rows.append(row_adv("drop_lowest_coverage_quartile", "Drop lowest coverage quartile"))

    di = dbint.get("interaction", dbint)
    rows.append(
        f"Drop China and Saudi Arabia; re-standardize & {pp(di['estimate'])} & {pval(di['p_cluster'])} & "
        f"{intfmt(dbint['N'])} & {dbint['G']} & indep.\\ reproduced \\\\"
    )
    cx = ctrlx["with_control_by_moderator"]
    rows.append(
        f"+ control $\\times$ moderator (post-registration) & {pp(cx['estimate'])} & {pval(cx['p_cluster'])} & "
        f"{intfmt(ctrlx['N'])} & {ctrlx['G']} & post-reg., dual impl. \\\\"
    )
    rows.append(r"\addlinespace")

    loo = exp["robustness"]["M6_9_leave_one_out"]
    boot = exp["robustness"]["M6_7_economy_block_bootstrap"]
    summ = adv["summary"]
    sr = adv["sign_reversal_algebra_check"]
    rows.append(
        f"Leave out each of 7 world regions & {{{pp(summ['leave_region_max'])} \\ldots\\ {pp(summ['leave_region_min'])}}} & "
        f"\\multicolumn{{3}}{{l}}{{all negative}} & \\\\"
    )
    rows.append(
        f"Leave out each of 97 economies & {{{pp(loo['max'])} \\ldots\\ {pp(loo['min'])}}} & "
        f"\\multicolumn{{3}}{{l}}{{all negative; {loo['sign_reversals']} sign reversals}} & \\\\"
    )
    rows.append(
        f"Economy-block bootstrap (999) & {pp(boot['estimate'])} & "
        f"\\multicolumn{{3}}{{l}}{{95\\% percentile CI {ci(boot['ci95_percentile'][0], boot['ci95_percentile'][1])}}} & \\\\"
    )
    rows.append(
        f"Moderator sign reversed (algebra check) & {{{pp(sr['estimate'])}}} & "
        f"\\multicolumn{{3}}{{l}}{{exact negation of the baseline}} & \\\\"
    )

    logit = t6row("M6_2_logit_interaction_AME")
    probit = t6row("M6_2_probit_interaction_AME")

    body = rf"""\begin{{table}}[htbp]
\centering
\caption{{The M2 interaction $\beta_3$ across specifications (percentage points per SD).}}
\label{{tab:robustness}}
\begin{{threeparttable}}
\begin{{tabular}}{{l r l r r l}}
\toprule
Specification & $\beta_3$ & $p$ & $N$ & $G$ & Note \\
\midrule
{chr(10).join(rows)}
\bottomrule
\end{{tabular}}
\begin{{tablenotes}}[flushleft]\footnotesize
\item All specifications are M2-form (percentage points per one economy-level SD of the
negative coverage $z$-score), economy-clustered (CR1). All rows were reproduced by the
independent cold implementation \texttt{{CLAUDE-S5R-20260910-001}}; the China/Saudi-Arabia
row was additionally reproduced by \texttt{{CLAUDE-S5R-DB-INTEGRITY-20260910-001}}
($|\Delta|=5\times10^{{-14}}$) and the control-by-moderator row by
\texttt{{CODEX-S5-CTRLXMOD-REPRO-20260910-001}} ($|\Delta|=3\times10^{{-13}}$). The
control-by-moderator row is a post-registration check outside the frozen quantity set.
Dummy-variable logit and probit interaction average marginal effects are
${pp(logit['estimate'])}$ and ${pp(probit['estimate'])}$ percentage points (same sign).
\end{{tablenotes}}
\end{{threeparttable}}
\end{{table}}"""
    write("tab_robustness.tex", body)


# ---------------------------------------------------------------- macros -------

def build_macros() -> None:
    def t2get(panel, var, field="weighted_mean"):
        return float(next(r for r in t2 if r["panel"] == panel and r["variable"] == var)[field])

    raw_nodig = t2get("anydigpayment_0", "formal_borrow") * 100
    raw_dig = t2get("anydigpayment_1", "formal_borrow") * 100
    reg = comp.get("economies_by_world_bank_region", {})

    def rget(frag):
        return str(next((v for k, v in reg.items() if frag in k), "?"))

    m1b1 = models["M1"]["coefficients"]["anydigpayment"]
    m2b1 = models["M2"]["coefficients"]["anydigpayment"]
    m2b3 = models["M2"]["coefficients"]["anydigpayment:lowcov2019_z"]
    m2b = models["M2b"]["coefficients"]["anydigpayment:lowcov2019_bmedian"]
    m3a_r = models["M3a"]["coefficients"]["receive_dig"]
    m3a_m = models["M3a"]["coefficients"]["make_dig"]
    m3b_r = models["M3b"]["coefficients"]["receive_dig:lowcov2019_z"]
    m3b_m = models["M3b"]["coefficients"]["make_dig:lowcov2019_z"]
    inf3 = models["M4_informal_borrow"]["coefficients"]["anydigpayment:lowcov2019_z"]
    m2c = exp["primary"]["M2c_joint"]
    cx = ctrlx["with_control_by_moderator"]
    di = dbint.get("interaction", dbint)
    fb_mean = desc["weighted_means"]["formal_borrow"]
    mde = (1.959963985 + 0.841621234) * m2b3["se_cluster"]

    def mac(name, val):
        return f"\\newcommand{{\\{name}}}{{{val}}}"

    lines = [
        HEADER.rstrip(),
        "% In-text statistics. Regenerate via build_tables.py; never edit by hand.",
        mac("NAdults", intfmt(models["M1"]["N"])),
        mac("NEconomies", str(models["M1"]["G"])),
        mac("NMechAdults", intfmt(models["M3a"]["N"])),
        mac("NMechEconomies", str(models["M3a"]["G"])),
        mac("FormalBorrowMean", num(fb_mean * 100, 1)),
        mac("MOneBeta", pp(m1b1["estimate"], 3)),
        mac("MOneSE", pp(m1b1["se_cluster"], 3)),
        mac("MOneCIlo", pp(m1b1["ci95"][0], 3)),
        mac("MOneCIhi", pp(m1b1["ci95"][1], 3)),
        mac("MTwoBetaOne", pp(m2b1["estimate"], 3)),
        mac("MTwoBetaThree", pp(m2b3["estimate"], 3)),
        mac("MTwoBetaThreeSE", pp(m2b3["se_cluster"], 3)),
        mac("MTwoBetaThreeCIlo", pp(m2b3["ci95"][0], 3)),
        mac("MTwoBetaThreeCIhi", pp(m2b3["ci95"][1], 3)),
        mac("MTwoBetaThreeP", pval(m2b3["p_cluster"])),
        mac("MTwoBmedianBeta", pp(m2b["estimate"], 3)),
        mac("MTwoBmedianSE", pp(m2b["se_cluster"], 3)),
        mac("MTwoBmedianP", pval(m2b["p_cluster"])),
        mac("MtwocF", num(m2c["F"], 2)),
        mac("MtwocP", pval(m2c["p_cluster"])),
        mac("MThreeAReceive", pp(m3a_r["estimate"], 3)),
        mac("MThreeAMake", pp(m3a_m["estimate"], 3)),
        mac("MThreeBReceive", pp(m3b_r["estimate"], 3)),
        mac("MThreeBReceiveP", pval(m3b_r["p_cluster"])),
        mac("MThreeBMake", pp(m3b_m["estimate"], 3)),
        mac("MThreeBMakeP", pval(m3b_m["p_cluster"])),
        mac("InformalBetaThree", pp(inf3["estimate"], 3)),
        mac("InformalBetaThreeP", pval(inf3["p_cluster"])),
        mac("InformalBetaThreeQ", num(bh["informal_b3"]["q_bh"], 3)),
        mac("InformalN", intfmt(models["M4_informal_borrow"]["N"])),
        mac("CtrlxModBeta", pp(cx["estimate"], 3)),
        mac("CtrlxModSE", pp(cx["se_cluster"], 3)),
        mac("CtrlxModP", pval(cx["p_cluster"])),
        mac("CtrlxModCIlo", pp(cx["ci95"][0], 2)),
        mac("CtrlxModCIhi", pp(cx["ci95"][1], 2)),
        mac("WithinRtwoBase", num(wr2["within_r2_baseline_M2"], 4)),
        mac("WithinRtwoFull", num(wr2["within_r2_with_control_by_moderator"], 4)),
        mac("DBIntBeta", pp(di["estimate"], 3)),
        mac("DBIntP", pval(di["p_cluster"])),
        mac("DBIntN", intfmt(dbint["N"])),
        mac("DBIntG", str(dbint["G"])),
        mac("MDEpp", num(mde * 100, 2)),
        mac("VnmSlope", num(vnm["m2_implied_association"] * 100, 2)),
        mac("VnmSlopeCIlo", num(m7ci.get("ci95_pp", [3.87, 6.27])[0], 2)),
        mac("VnmSlopeCIhi", num(m7ci.get("ci95_pp", [3.87, 6.27])[1], 2)),
        mac("VnmCoverage", num(vnm["any_cov"], 1)),
        mac("SampleMedianCoverage", "40.4"),
        mac("ThinCoverageEconomies", str(comp.get("coverage_below_10_economies", 24))),
        mac("ThinShareN", intfmt(comp.get("coverage_below_10_respondents", 23458))),
        mac("ThinSharePct", num(comp.get("coverage_below_10_respondent_share", 0.23327) * 100, 1)),
        mac("RawRateNoDig", num(raw_nodig, 2)),
        mac("RawRateDig", num(raw_dig, 2)),
        mac("RawGap", num(raw_dig - raw_nodig, 1)),
        mac("RegionSSA", rget("Sub-Saharan Africa")),
        mac("RegionECA", rget("Europe & Central Asia")),
        mac("RegionLAC", rget("Latin America")),
        mac("RegionMENA", rget("Middle East")),
        mac("RegionEAP", rget("East Asia")),
        mac("RegionSA", rget("South Asia")),
        mac("RegionHIC", rget("High income")),
    ]
    OUT_MACRO.parent.mkdir(parents=True, exist_ok=True)
    OUT_MACRO.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"  wrote {OUT_MACRO.relative_to(PROJECT)}")


# ---------------------------------------------------------------- main --------

def main() -> None:
    print("Building Study 5 manuscript tables:")
    build_sample()
    build_descriptives()
    build_primary()
    build_mechanism()
    build_secondary()
    build_robustness()
    build_macros()
    manifest = {
        "generated_utc": datetime.now(timezone.utc).isoformat(),
        "builder": "code/study_05_crosscountry/tables/build_tables.py",
        "sources": [
            "results/stage2/CODEX-S5-TABLES-20260909-001/T1_drop_table.csv",
            "results/stage2/CODEX-S5-TABLES-20260909-001/T2_descriptives.csv",
            "results/stage2/CODEX-S5-TABLES-20260909-001/T4_mechanism.csv",
            "results/stage2/CODEX-S5-TABLES-20260909-001/T5_secondary_placebo.csv",
            "results/stage2/CODEX-S5-TABLES-20260909-001/T6_robustness.csv",
            "results/stage2/CODEX-S5-EXP-20260909-002/result.json",
            "results/stage2/CODEX-S5-EXP-20260909-002/interaction_grid.csv",
            "results/stage3/CODEX-S5-DB-INTEGRITY-20260910-001/result.json",
            "results/stage3/CODEX-S5-CTRLXMOD-REPRO-20260910-001/result.json",
            "results/stage3/CLAUDE-S5R-CTRLXMOD-WR2-20260910-001/result.json",
            "results/stage3/CODEX-S5-SAMPLE-COMPOSITION-20260910-001/result.json",
        ],
        "outputs": sorted(p.name for p in OUT_TAB.glob("*.tex")) + ["estimates.tex"],
    }
    (OUT_TAB.parent / "table_build_manifest.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    print("  wrote manuscript/table_build_manifest.json")
    print("done.")


if __name__ == "__main__":
    main()
